language: generic
dist: jammy

python:
  - "3.11"

before_install:
  - sudo apt update

install:
  - pip3 install latex-rubber
  - sudo apt install -y opam texlive-full
  - opam init --auto-setup --disable-sandboxing --compiler=4.13.1
  - sudo apt upgrade texlive
  - pdflatex --version

before_script:
  - opam pin -y add ott patched-ott
  - opam upgrade -y -w ott
  - eval $(opam env)

script:
  - cd proofs
  - make
  - cd ../oopsla24
  - make

