language: generic
dist: jammy

before_install:
  # - sudo apt install -y latexmk
  - sudo apt update
  - sudo apt install -y opam texlive-full

install:
  - opam init --auto-setup --disable-sandboxing --compiler=4.13.1

before_script:
  - opam pin -y add ott patched-ott
  - opam upgrade -y -w ott

script:
  - cd proofs
  - make


