language: generic
dist: xenial

before_install:
  - sudo add-apt-repository -y ppa:avsm/ppa
  - sudo apt-get update
  - sudo apt-get install -y latexmk
  - sudo apt-get install -y opam texlive-full

install:
  - opam init --auto-setup --disable-sandboxing --compiler=4.13.1
  - eval $(opam env)

before_script:
  - opam pin -y add ott patched-ott
  - opam upgrade -y -w ott

script:
  - cd proofs
  - make


