name: Makefile CI

on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up OCaml environment
        uses: docker://ocaml/opam
        
      - name: Get patched-ott repository
        run: |
          git pull https://github.com/demarkok/ott.git patched-ott
          opam pin add ott patched-ott
          opam upgrade -w ott
          
      - name: Install make
        run: apk add make
          
      - name: Build LaTeX
        run: |
          cd proofs
          make
