name: Makefile CI

on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 5.1
      - run: git clone https://github.com/demarkok/ott.git patched-ott
      - run: opam pin add ott patched-ott
      - run: opam upgrade -w ott
      - run: eval $(opam env)
      - run: cd proofs
      - run: make
